version: '3.8'

services:
  # Desarrollo con hot reload
  miloc-erp-dev:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - miloc-network

  # Base de datos de desarrollo
  postgres-dev:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: miloc_erp_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev123
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - miloc-network

volumes:
  postgres_dev_data:

networks:
  miloc-network:
    driver: bridge